global_system_prompt = """You are a researcher in computer science and you analyze scientific papers and datasets.
    You answer only the truth, based on the facts from the given text.
    You are focused on quality and properties of datasets."""
# setting as false reduces evaluation time since the vector database is not being initiated for every reference
use_vector_database = false
global_vector_db_chunk_size = 500
global_vector_db_chunk_overlap = 0


[[prompts]]
field_name = "paper_title"
system_prompt = ""
prompt = """
What is the title of the provided paper?
Include only the paper title in your response.
Answer should look like this:
NetTiSA: Extended IP flow with time-series features for universal
bandwidth-constrained high-speed network traffic classification
"""
response_type = "string"
search_method = "regex"
chars_before = 0
chars_after = 2000
[[prompts.keywords]]
keyword = ""


[[prompts]]
field_name = "publication_year"
system_prompt = ""
prompt = """
What year was the provided paper published?
Include only the year in your response.
Answer should look like this:
2022
"""
response_type = "string"
search_method = "regex"
chars_before = 0
chars_after = 2000
[[prompts.keywords]]
keyword = ""

