[[substitution_rules]]
regex = "-\\s*\n"
replace_with = ""

[[substitution_rules]]
regex = "–\\s*\n"
replace_with = ""

[[substitution_rules]]
regex = "—\\s*\n"
replace_with = ""

[[substitution_rules]]
regex = "ﬃ"
replace_with = "ffi"

[[substitution_rules]]
regex = "ﬁ"
replace_with = "fi"

[[substitution_rules]]
regex = "ﬀ"
replace_with = "ff"

[[substitution_rules]]
regex = "ﬂ"
replace_with = "fl"

[[substitution_rules]]
regex = "ﬄ"
replace_with = "ffl"

[[substitution_rules]]
regex = "ﬆ"
replace_with = "st"