# input files
#input_analysis_file = "../in/quic_input.toml"
#input_direct_analysis_paper_file = "../resources/quic_paper.pdf"
#input_reference_papers_directory = "../resources/quic_references"
# output files
#output_main_analysis_file = "../out/main_analysis_quic37.toml"
#output_per_paper_reference_analysis_file = "../out/per_paper_reference_analysis37_quic.toml"
# troubleshooting output files
#output_direct_analysis_debug_file = "../out/debug/main_analysis37_quic.toml"
#output_reference_analysis_debug_file = "../out/debug/reference_analysis37_quic.toml"

input_analysis_file = "../in/miner22-example.toml"
input_direct_analysis_paper_file = "../in/cesnet-miner-22-paper.pdf"
input_reference_papers_directory = "../in/cited"
# output files
output_main_analysis_file = "../out/main_analysis_miner_22_example.toml"
output_per_paper_reference_analysis_file = "../out/per_paper_reference_miner_22_example.toml"
# troubleshooting output files
output_direct_analysis_debug_file = "../out/debug/main_analysis_miner_22_example.toml"
output_reference_analysis_debug_file = "../out/debug/reference_analysis_miner_22_example.toml"
