global_system_prompt = """You are a researcher in computer science and you analyze scientific papers and datasets.
    You answer only the truth, based on the facts from the given text.
    You are focused on quality and properties of datasets.
    You are filling out a structured analysis, so your responses must be short and information dense."""
#global_system_prompt = ""
global_chars_before = 1000
global_chars_after = 3000
global_summarization_prompt = """
    This is a concatenation of insights about a dataset gained from many sources.
    Summarize this information into a 10 or less points without any redundancy.
    """

[[prompts]]
field_name = "dataset_application"
system_prompt = ""
prompt = """These are snippets from a scientific paper which has cited the paper of your interest.
    The paper of interest describes a dataset of network data flow.
    The dataset you are interested in is called __dataset_title__ and its paper has reference number of [__citation_number__].
    The goal is to find out if the dataset was used by the authors of the paper, or whether it was only referenced.
    If the dataset was actually used, you can also figure out for what application it was used, but only if the paper mentions it explicitly.
    If the paper mentions f1-score or other classification metrics achieved using the dataset of interest, include it in the response.
    Answer should be only one phrase long.
    Aswer must only contain short structured response exactly as provided in following examples including brackets.
    Answer should look like this: [used, application: machine learning]
    Another example: [used, application: unknown]
    Another example: [cited]"
    """
response_type = "string"
default_value = "only cited"
aggregation_method = "concatenate"
concatenation_format = "* [__index__][] __paper_title__; [__response__][]"
aggregation_skip_default = false


[[prompts]]
field_name = "key_observations"
system_prompt = ""
prompt = """These are snippets from a scientific paper which has cited our paper.
    Our paper describes a dataset of network data flow.
    Your goal is to find the key observations from our dataset.
    List only observations that are explicitly written in the paper.
    If you think there are no observations from our dataset mentioned or if you are not sure, reply just "no key observations found".
    List only observations regarding our dataset and therefore our paper.
    The dataset you are interested in is called __dataset_title__ and its paper has reference number of [__citation_number__].
    Reply in 5 or less single line points.
    """
response_type = "string"
default_value = "no key observations found"
aggregation_method = "concatenate"
concatenation_format = "** [__index__] __paper_title__:**\n __response__"
aggregation_skip_default = false


[[prompts]]
field_name = "known_issues"
system_prompt = ""
prompt = """These are snippets from a scientific paper which has cited our paper.
    Our paper describes a dataset of network data flow.
    Your goal is to find any issues in our dataset.
    List only issues that are explicitly written in the paper.
    If you think there are no issues with our dataset mentioned or if you are not sure, reply just "no issues found".
    Also, list only issues regarding our dataset and therefore our paper.
    The dataset you are interested in is called __dataset_title__ and its paper has reference number of [__citation_number__].
    Reply in 5 or less single line points.
    """
response_type = "string"
default_value = "no issues found"
aggregation_method = "concatenate"
concatenation_format = "** [__index__] __paper_title__:**\n __response__"
aggregation_skip_default = false


[[prompts]]
field_name = "sentiment"
system_prompt = ""
prompt = """These are snippets from a scientific paper which has cited our paper.
    Our paper describes a dataset of network data flow.
    Your goal is to evaluate sentiment in which paper talks about our dataset.
    The dataset you are interested in is called __dataset_title__ and its paper has reference number of [__citation_number__].
    Answer can contain only the sentiment rating (number from -5 to 5, -5 is very negative, 0 is neutral, 5 is very positive).
    ### Example:
    1
    ### Example:
    -4
    """
response_type = "integer"
default_value = "not referenced"
aggregation_method = "value_counts"
aggregation_skip_default = false
