acronym_info = "Short name of the dataset, which is used as the unique identifier. E.g., CESNET_TLS_Year22"
dataset_title = "CESNET-MINER22"
acronym_aliases_info = "Additional alias for the Dataset Acronym (e.g. CESNET-TLS-Year22-XS). Used to filter the different subsection of the original dataset"
acronym_aliases = "CESNET-MINER22"
title_info = "Full title of the dataset. E.g., CESNET-TLS-Year22"
title = ""
paper_title_info = "Full title of the original paper with the dataset"
paper_title = "DeCrypto: Finding cryptocurrency miners on ISP networks"
authors = "Richard Plný, Karel Hynek, Tomáš Čejka"
description_info = "High-level description of the dataset. E.g., TLS capture from CESNET2 backbone network over one year (2022). The capture was done using high-speed monitoring probes at the perimeter of CESNET2 network. This dataset provides realistic characteristics of traffic originating from various web browsers, operating systems, mobile devices, desktop machines, and both HTTP/1.1 and HTTP/2 protocols."
description = "Datasets of cryptomining communication captured on CESNET2 during December 2021 to February 2022 and March 2022."
format_info = "Dataset data format. E.g. json, csv, datazoo"
format = "csv"
doi_info = "DOI of this dataset"
doi = "https://doi.org/10.5281/zenodo.7189293"
origins_doi_info = "DOI of the original dataset"
origins_doi = ""
date_submitted = 2024-09-05T13:00:26.427000
submitter = "Richard Plný <plnyrich@fit.cvut.cz>"
status = "accepted"
tags = "cryptomining,  cryptomalware"
url = "https://zenodo.org/records/7189293/files/DeCryptoDatasets.tar.gz?download=1"
files = []
versions = ""
analysis_status = "Requested"
filename = ""
label_name = "string LABEL"

[collection_workflow]
data_collection_tool = "ipfixprobe"
data_collection_year = "2022"
feature_extraction_tool_info = "Tool that converts dataset to feature dataset. If any."
feature_extraction_tool = "ipfixprobe PSTATS + manual script preprocesing (unknown script)"
feature_extraction_tool_description = "There is Per Packet Information (PPI) information but is is not flattened. Categorical info from basic (SRC_PORT, DST_PORT, TCP_FLAGS, PROTOCOL) ipfixprobe module is kept in the dataset."
capture_config_parameters_info = "specific parameters that were used to capture dataset or feature dataset"
capture_config_parameters = "five minutes of active timeout"
real_dataset_info = "Source of the dataset. E.g., real environment, testbed or generated."
real_dataset = "yes"
annotation_info = "Description of the dataset annotation. E.g., manual, automatic"
annotation = "automatic using blocklist"


[generic_info]
capture_dates_info = "When was the dataset captured/generated"
capture_dates = "Dec 2021 - Feb 2022 (Design), - March 2022 (Evaluation)"
classes = "2"
features = "16"
f1-score_info = "F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM]"
f1-score = "n/a"
performance_metric_info = "Perfomance metric defined by the author. Please define full specification e.g., F1-weighted"
performance_metric_name = "Accuracy"
performance_metric_value = "93.0% (Design), 86.46% (Evalaution)"
label_info = "Name of the field with label. In case this is unsupervised dataset, type None"
label = "string LABEL"
known_issues_info = """Description of indentified issues in the dataset"""
known_issues = """ """
key_observations_info = "List of known errors, drifts, limits, ... of the dataset"
key_observations = """

* The dataset has default split that avoids overfitting and variation with random sampling. There is split called Design and Evaluation.
* Two annotated datasets containing real-world traffic. Together
they contain more than 1 million extended bidirectional flow records of cryptominers communication and around 1.8 million records of other types of
traffic used as a counter class.
* Paper Plný, R., Hynek, K., Čejka, T.: Datasets of cryptomining communication (2022). https://doi.org/10.5281/zenodo.7189292, introduces the same dataset but with older name - Decrypto
* NetTiSA featureset improves ML score compared to originall Decrypto [2] and has the highest ML performance resutls
* The dataset contains field names with datatypes (could be redundant for ML analysis)
* Since the dataset contains two classes (one general and one specific for cryptomining) it is simple and redundant dataset for classification
* The Design dataset has 0 small classes, 3429 duplicated samples, 0 nan value 
* The Evaluation dataset has 0 small classes, 409 duplicated samples, 0 nan value
"""
dataset_organization_info = "Structure of the dataset. E.g., per day, per capture, per device"
dataset_organization = "per capture"
dataset_organization_description_info = "Description of the content of the organization. Is there any metadata?"
dataset_organization_description = "The dataset is splitted in two files called Design and Evaluation which contains two continuous captures from different dates."
dataset_documentation_info = "How to get started with the dataset. Ideally add example notebook."
dataset_documentation = " Use get-dataset.py and Zenodo repository"
used_dataset_info = "Script to get dataset for provided analysis"
used_dataset = "get-dataset.py"
dataset_application_info = "Where the dataset has been already applied."
dataset_application = """
* [1] 10.23919/CNSM59352.2023.10327904, Koumar, Josef, Richard Plný, and Tomáš Čejka. "Enhancing DeCrypto: Finding Cryptocurrency Miners Based on Periodic Behavior [used, input to create Flow Time Series (FTS) featuredataset and detect periodicity]
* [2] https://doi.org/10.1016/j.comnet.2023.110147, Koumar, Josef, et al. "NetTiSA: Extended IP flow with time-series features for universal bandwidth-constrained high-speed network traffic classification. [used, calculate new featureset and got better results than originall version]
* [3] Koumar, Josef, Karel Hynek, and Tomáš Čejka. "Network traffic classification based on single flow time series analysis. [used, calculate new featureset and got better results than originall version]
* [4] https://doi.org/10.1007/978-3-031-22295-5_8, DeCrypto: Finding Cryptocurrency Miners on ISP Networks [used, create Decrypto dataset which was later renamed to CESNET-MINER22]
"""

per_class_data = """
{"Miner": 695496 (Design)/ 392577 (Evaluation), 
"Other": 1329407 (Design)/ 682999 (Evaluation)}
 """

per_feature_data ="""
{
    "uint64 BYTES": "Number of transferred bytes (from client to server)",
    "uint64 BYTES_REV": "Number of transferred bytes in the opposite direction (from server to client)",
    "time TIME_FIRST": "Time of interception of the first packet in the flow",
    "time TIME_LAST": "Time of interception of the last packet in the flow",
    "uint32 PACKETS": "Number of transferred packets (from client to server)",
    "uint32 PACKETS_REV": "Number of transferred packets in the opposite direction (from server to client)",
    "uint16 DST_PORT": "Destination port",
    "uint16 SRC_PORT": "Source port",
    "uint8 PROTOCOL": "Used protocol on the Transport layer of the ISO/OSI, TCP is represented by the value 6",
    "uint8 TCP_FLAGS": "TCP flags of the first packet (sent by client)",
    "uint8 TCP_FLAGS_REV": "TCP flags of the first packer from the opposite direction (sent by server)",
    "string LABEL": "Flow label. Possible values are: Miner, Other",
    "int8* PPI_PKT_DIRECTIONS": "Array of directions of the first 30 packets, values: 1 represents direction client->server, -1 represents direction server->client",
    "uint8* PPI_PKT_FLAGS": "Array of TCP flags of the first 30 packets",
    "uint16* PPI_PKT_LENGTHS": "Array of packet sizes of the first 30 packets",
    "time* PPI_PKT_TIMES": "Array of timestamps of intercept of the first 30 packets"
}
"""

[dataset_drift_analysis]
description = "Not evaluated"

[advanced_metrics]
description = "Not evaluated"

[dataset_comparison]
description = "Not evaluated"